name: Deploy Painel Admin

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar dependências
        run: |
          npm ci --legacy-peer-deps
      
      - name: Verificar estrutura do projeto
        run: |
          echo "Verificando estrutura de pastas..."
          ls -la ./src
          echo "Conteúdo da pasta src/pages:"
          ls -la ./src/pages || echo "Pasta pages não encontrada"
          echo "Conteúdo da pasta src/app:"
          ls -la ./src/app || echo "Pasta app não encontrada"
      
      - name: Verificar conflitos de diretórios
        run: |
          if [ -d "./src/app/pages" ]; then
            echo "AVISO: Detectada estrutura conflitante src/app/pages"
            echo "Corrigindo temporariamente..."
            mkdir -p ./src/app/pages_temp
            mv ./src/app/pages/* ./src/app/pages_temp/ || true
            rm -rf ./src/app/pages
          fi
      
      - name: Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build
        env:
          CI: false  # Permite que o build continue mesmo com warnings
          NEXT_TELEMETRY_DISABLED: 1
      
      - name: Restaurar estrutura original
        if: always()
        run: |
          if [ -d "./src/app/pages_temp" ]; then
            echo "Restaurando estrutura original..."
            mkdir -p ./src/app/pages
            mv ./src/app/pages_temp/* ./src/app/pages/ || true
            rm -rf ./src/app/pages_temp
          fi
      
      - name: Construir e publicar imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/viralizamos/painel-admin:latest
          build-args: |
            NODE_ENV=production
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy para produção
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/viralizamos
            docker-compose pull painel
            docker-compose up -d painel
            docker system prune -f 